OPEN-29 Cleanup: removed extra qualification ‘LLDir_Win32::’ on member ‘getNextFileInDir’
Before OPEN-29, when lldir_win32.h would have been included when
building for Linux, GCC would error out with
	indra/llvfs/lldir_win32.h:50: error: extra qualification ‘LLDir_Win32::’ on member ‘getNextFileInDir’
which, although unintended, probably was a Good Thing (TM), as this
would have aborted the build, so that the wrong include would be
noticed. Now that we explicitly error out with a (hopefully) useful
error message, this isn't needed anymore.